// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/tray/status.proto

package statuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	TimeStamp     int64                  `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_tray_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tray_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_tray_status_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Status) GetTimeStamp() int64 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Status) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StatusStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*StatusStreamMessage_Status
	//	*StatusStreamMessage_PullRequest
	Content       isStatusStreamMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusStreamMessage) Reset() {
	*x = StatusStreamMessage{}
	mi := &file_proto_tray_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusStreamMessage) ProtoMessage() {}

func (x *StatusStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tray_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusStreamMessage.ProtoReflect.Descriptor instead.
func (*StatusStreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_tray_status_proto_rawDescGZIP(), []int{1}
}

func (x *StatusStreamMessage) GetContent() isStatusStreamMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StatusStreamMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Content.(*StatusStreamMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StatusStreamMessage) GetPullRequest() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Content.(*StatusStreamMessage_PullRequest); ok {
			return x.PullRequest
		}
	}
	return nil
}

type isStatusStreamMessage_Content interface {
	isStatusStreamMessage_Content()
}

type StatusStreamMessage_Status struct {
	// client send
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type StatusStreamMessage_PullRequest struct {
	// server pull
	PullRequest *emptypb.Empty `protobuf:"bytes,2,opt,name=pull_request,json=pullRequest,proto3,oneof"`
}

func (*StatusStreamMessage_Status) isStatusStreamMessage_Content() {}

func (*StatusStreamMessage_PullRequest) isStatusStreamMessage_Content() {}

var File_proto_tray_status_proto protoreflect.FileDescriptor

const file_proto_tray_status_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tray/status.proto\x12\x04tray\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x06Status\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x1c\n" +
	"\tTimeStamp\x18\x02 \x01(\x03R\tTimeStamp\x12\x10\n" +
	"\x03Msg\x18\x03 \x01(\tR\x03Msg\"\x85\x01\n" +
	"\x13StatusStreamMessage\x12&\n" +
	"\x06status\x18\x01 \x01(\v2\f.tray.StatusH\x00R\x06status\x12;\n" +
	"\fpull_request\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\vpullRequestB\t\n" +
	"\acontent2Y\n" +
	"\rStatusService\x12H\n" +
	"\fStreamStatus\x12\x19.tray.StatusStreamMessage\x1a\x19.tray.StatusStreamMessage(\x010\x01B1Z/github.com/ruokeqx/grpcdemo/proto/tray/statuspbb\x06proto3"

var (
	file_proto_tray_status_proto_rawDescOnce sync.Once
	file_proto_tray_status_proto_rawDescData []byte
)

func file_proto_tray_status_proto_rawDescGZIP() []byte {
	file_proto_tray_status_proto_rawDescOnce.Do(func() {
		file_proto_tray_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tray_status_proto_rawDesc), len(file_proto_tray_status_proto_rawDesc)))
	})
	return file_proto_tray_status_proto_rawDescData
}

var file_proto_tray_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tray_status_proto_goTypes = []any{
	(*Status)(nil),              // 0: tray.Status
	(*StatusStreamMessage)(nil), // 1: tray.StatusStreamMessage
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_proto_tray_status_proto_depIdxs = []int32{
	0, // 0: tray.StatusStreamMessage.status:type_name -> tray.Status
	2, // 1: tray.StatusStreamMessage.pull_request:type_name -> google.protobuf.Empty
	1, // 2: tray.StatusService.StreamStatus:input_type -> tray.StatusStreamMessage
	1, // 3: tray.StatusService.StreamStatus:output_type -> tray.StatusStreamMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tray_status_proto_init() }
func file_proto_tray_status_proto_init() {
	if File_proto_tray_status_proto != nil {
		return
	}
	file_proto_tray_status_proto_msgTypes[1].OneofWrappers = []any{
		(*StatusStreamMessage_Status)(nil),
		(*StatusStreamMessage_PullRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tray_status_proto_rawDesc), len(file_proto_tray_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tray_status_proto_goTypes,
		DependencyIndexes: file_proto_tray_status_proto_depIdxs,
		MessageInfos:      file_proto_tray_status_proto_msgTypes,
	}.Build()
	File_proto_tray_status_proto = out.File
	file_proto_tray_status_proto_goTypes = nil
	file_proto_tray_status_proto_depIdxs = nil
}
